name: Jenkins CI Pipeline

on: [push]

#env:
 # my_user_var: ${{ secrets.JENKINS_USER }}
 # my_api_token: ${{ secrets.JENKINS_API_TOKEN }}
 # my_token_name: ${{ vars.TOKEN_NAME }}
  
jobs:
  integration_job:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Jenkins Job
        run: |
          echo "Getting CSRF crumb..."
          CRUMB_JSON=$(curl -s -u "$JENKINS_USER:$JENKINS_API_TOKEN" \
            https://94a60f8a7dcf.ngrok-free.app/crumbIssuer/api/json)
      
          echo "CRUMB_JSON: $CRUMB_JSON"
      
          CRUMB=$(echo "$CRUMB_JSON" | jq -r '.crumb')
          CRUMB_FIELD=$(echo "$CRUMB_JSON" | jq -r '.crumbRequestField')
      
          echo "Triggering Jenkins job with crumb..."
          curl -X POST "https://94a60f8a7dcf.ngrok-free.app/view/all/job/course_end_project_1/build?token=$TOKEN_NAME" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN" \
            -H "$CRUMB_FIELD: $CRUMB"
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          TOKEN_NAME: ${{ vars.TOKEN_NAME }}


